"""add settings

Revision ID: 363f5663deca
Revises: 572740b7511b
Create Date: 2025-11-29 01:30:59.136505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363f5663deca'
down_revision = '572740b7511b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation', sa.String(), nullable=True),
    sa.Column('filter', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_settings_conversation'), 'conversation_settings', ['conversation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_settings_conversation'), table_name='conversation_settings')
    op.drop_table('conversation_settings')
    # ### end Alembic commands ###
